# Generated by Django 2.0 on 2018-06-25 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_auto_20180625_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='tooy',
            new_name='root',
        ),
    ]
